services:
  - type: web
    name: pedestrian-volume-api
    env: docker
    branch: master  # Changed from main to match your current branch
    rootDir: pedestrian-api
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /usr/src/app
    # Increase build timeout for dependencies
    buildCommand: echo "Building with Docker..."
    # Configure auto-deploy
    autoDeploy: true
